#!/usr/bin/env python3
"""Generate usb_case_config.generated.h from experiment case JSON."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "firmware" / "include" / "usb_case_config.generated.h"
DEFAULT_CASES_DIR = REPO_ROOT / "experiments" / "cases"

REQUIRED_FIELDS = (
    "case_id",
    "name",
    "group",
    "base_persona",
    "mutation",
)


def _to_c_string_literal(value: str) -> str:
    """Return a C string literal content with conservative escaping.

    Output is ASCII-only by escaping non-ASCII bytes as octal sequences.
    """
    out: list[str] = []
    for b in value.encode("utf-8"):
        if b == 0x22:  # "
            out.append(r"\"")
        elif b == 0x5C:  # \\
            out.append(r"\\")
        elif b == 0x0A:
            out.append(r"\n")
        elif b == 0x0D:
            out.append(r"\r")
        elif b == 0x09:
            out.append(r"\t")
        elif 0x20 <= b <= 0x7E:
            out.append(chr(b))
        else:
            out.append(f"\\{b:03o}")
    return "".join(out)


def _load_case(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValueError(f"Case file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object in {path}")

    missing = [field for field in REQUIRED_FIELDS if field not in data]
    if missing:
        raise ValueError(f"Missing required fields in {path}: {', '.join(missing)}")

    return data


def _parse_case_id(raw: Any, path: Path) -> int:
    if isinstance(raw, int):
        case_id = raw
    elif isinstance(raw, str):
        if not raw.isdigit():
            raise ValueError(f"Field 'case_id' must contain digits in {path}: {raw!r}")
        case_id = int(raw, 10)
    else:
        raise ValueError(f"Field 'case_id' must be string/int in {path}")

    if case_id < 0:
        raise ValueError(f"Field 'case_id' must be non-negative in {path}")

    return case_id


def _require_string(data: dict[str, Any], key: str, path: Path) -> str:
    value = data.get(key)
    if not isinstance(value, str):
        raise ValueError(f"Field {key!r} must be a string in {path}")
    return value


def _generate_header(case_data: dict[str, Any], case_path: Path) -> str:
    case_id = _parse_case_id(case_data["case_id"], case_path)
    name = _require_string(case_data, "name", case_path)
    group = _require_string(case_data, "group", case_path)
    base_persona = _require_string(case_data, "base_persona", case_path)
    mutation = _require_string(case_data, "mutation", case_path)

    return "\n".join(
        [
            "#ifndef USB_CASE_CONFIG_GENERATED_H",
            "#define USB_CASE_CONFIG_GENERATED_H",
            "",
            "/* Auto-generated by tools/gen_usb_case_config.py. Do not edit manually. */",
            f"/* Source: {case_path.as_posix()} */",
            "",
            f"#define USB_CASE_ID {case_id}u",
            f"#define USB_CASE_NAME \"{_to_c_string_literal(name)}\"",
            f"#define USB_CASE_GROUP \"{_to_c_string_literal(group)}\"",
            f"#define USB_CASE_BASE_PERSONA \"{_to_c_string_literal(base_persona)}\"",
            f"#define USB_CASE_MUTATION_SUMMARY \"{_to_c_string_literal(mutation)}\"",
            "",
            "#endif /* USB_CASE_CONFIG_GENERATED_H */",
            "",
        ]
    )


def _list_cases(cases_dir: Path) -> int:
    if not cases_dir.is_dir():
        print(f"Cases directory not found: {cases_dir}", file=sys.stderr)
        return 2

    case_paths = sorted(cases_dir.glob("*.json"))
    if not case_paths:
        print("No case files found.")
        return 0

    for path in case_paths:
        try:
            data = _load_case(path)
            case_id = str(data.get("case_id", "?"))
            name = str(data.get("name", "?"))
            group = str(data.get("group", "?"))
            print(f"{path.as_posix()}\tcase_id={case_id}\tname={name}\tgroup={group}")
        except ValueError as exc:
            print(f"{path.as_posix()}\tINVALID\t{exc}")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate firmware/include/usb_case_config.generated.h from a case JSON file."
    )
    parser.add_argument("case_json", nargs="?", help="Path to experiments/cases/*.json file")
    parser.add_argument(
        "-o",
        "--output",
        default=str(DEFAULT_OUTPUT),
        help=f"Output header path (default: {DEFAULT_OUTPUT.as_posix()})",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help=f"List available case JSON files under {DEFAULT_CASES_DIR.as_posix()}",
    )

    args = parser.parse_args()

    if args.list:
        if args.case_json:
            parser.error("case_json must not be provided with --list")
        return _list_cases(DEFAULT_CASES_DIR)

    if not args.case_json:
        parser.error("case_json is required unless --list is used")

    case_path = Path(args.case_json).resolve()
    case_data = _load_case(case_path)
    header_text = _generate_header(case_data, case_path)

    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_text, encoding="utf-8")

    print(f"Generated {output_path} from {case_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
